name: Sync Upstream

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *' # 北京时间每天上午 8:00 自动运行
  workflow_dispatch:      # 允许你随时手动点击同步

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync Upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_repository: develop202/migu_video
          upstream_branch: main
          target_branch: main
          test_mode: false
